import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Press_Start_2P } from "next/font/google";

const press = Press_Start_2P({ subsets: ['latin'],
  variable: '--font-press',
  weight: '400'
 });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={press.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${press.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
